export default {
  headerBackground: "#1DA7DA",
  defaultBtnBackground: "#3dd07d",
  defaultBtnColor: "#fff",
  defaultBtnBackgroundHover: "#6AD4A0",
  contentHeaderBackground: "#1DA7DA",
  articleBackground: "#fff",
  headerBorderColor: "#3dd07d",
  articleBtnBackground: "#fff",
  articleBtnBorder: "#3dd07d",
  articleBtnColor: "#3dd07d",
  articleBtnBackgroundHover: "#3dd07d",
  articleBtnColorHover: "#fff",
  headerMainContentColor: "#fff",
  paragraphMainContentColor: "#fff",
  mainBtnBackground: "#F1358E",
  mainBtnBackgroundHover: "#F1358E",
  footerItemHoverColor: "#3dd07d",
  menuBackground: "#fff",
  media: {
    tablet: "screen and (min-width: 768px)",
    desktop: "screen and (min-width: 992px)",
  },
};
